---
# tasks file for ec2

- name: Creating Security Group for K8s cluster
  ec2_group:
    name: "{{ sg_name }}"
    description: Security Group for allowing all porti
    region: "{{ region_name }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
    - proto: all
      cidr_ip: 0.0.0.0/0
    rules_egress:
    - proto: all
      cidr_ip: 0.0.0.0/0
- name: Creating EC2 instances for Master & Worker Nodes
  amazon.aws.ec2_instance:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_size }}"
    image_id: "{{ ami_id }}"
    wait: true
    security_group: "{{ sg_name }}"
    count: 1
    vpc_subnet_id: "{{ subnet_name }}"
    network:
      assign_public_ip: true
    region: "{{ region_name }}"
    state: present
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    tags:
      Name: "{{ item }}"
  register: ec2
  loop: "{{ instance_tag }}"

- name: Add Master node to host group
  add_host:
    hostname: "{{ ec2.results[0].instances[0].public_ip_address }}"
    groupname: k8s_master

- name: Add 1st Worker Node to worker  host group
  add_host:
    hostname: "{{ ec2.results[1].instances[0].public_ip_address }}"
    groupname: k8s_worker

- name: Add 2nd Worker Node to worker hsot group
  add_host:
    hostname: "{{ ec2.results[2].instances[0].public_ip_address }}"
    groupname: k8s_worker

- name: Check for SSH to be availabel on port 22
  wait_for:
    host: "{{ ec2.results[2].instances[0].public_dns_name }}"
    port: 22
    state: started
